# Generated by Django 5.1.2 on 2024-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
